services:
  mariadb:
    build : ./requirements/mariadb/
    volumes:
     - ~/data/mysql:/var/lib/mysql
    networks:
     - back_end
    env_file:
      - ../.env
    restart: on-failure

  wordpress:
    build: ./requirements/wordpress/
    volumes:
      - ~/data/html:/var/www/html
    networks:
      - front_end
      - back_end
    depends_on:
      - mariadb
    env_file:
      - ../.env
    restart: on-failure

  nginx:
    build: ./requirements/nginx/
    ports:
    - 443:443
    volumes:
    - ~/data/html:/var/www/html
    networks:
      - front_end
    depends_on:
      - wordpress
    restart: on-failure
networks:
  front_end:
  back_end:
