services:
  mariadb:
    build : ./mariadb/
    volumes:
     - ~/Desktop/mysql:/var/lib/mysql
    networks:
     - back_end
    env_file:
      - .env
    restart: on-failure

  wordpress:
    build: ./wordpress/
    volumes:
      - ~/Desktop/html:/var/www/html
    networks:
      - front_end
      - back_end
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: on-failure

  nginx:
    build: ./nginx/
    ports:
    - 8080:443
    volumes:
    - ~/Desktop/html:/var/www/html
    networks:
      - front_end
    depends_on:
      - wordpress
    restart: on-failure
networks:
  front_end:
  back_end:
